#!/bin/sh

if [ $# -eq 0 ]
then
  echo -e "git-remote-clone server-addr. remote-directory\nExample: git-remote-clone some.server.com Projects/projectname"
  exit
fi

ssh $1 "mkdir $2.git && cd $2.git && git --bare init" && \
git remote add origin "ssh://$1/~/$2.git" && \
git config branch.master.remote origin && \
git config branch.master.merge refs/heads/master && \
git push --all && \
git fetch && \
echo "ref: refs/remotes/origin/master" > .git/refs/remotes/origin/HEAD
